### ISSUE TITLE
The safe mode does not seem to be available in the library

### ISSUE THREAD

**Issue by GitHubish** [crisp-im/crisp-sdk-web#1]
When we receive in the console the warning message asking us to activate the "safe mode" I see that it is not possible to do it from the exposed methods of the SDK. Shouldn't it be possible to activate it directly in the configure method?

`You can disable this warning by adding: $crisp.push(["safe", true]) to your page JavaScript.`

**Comment by noghartt** [comment]
The lib injects the `$crisp` object on `window` too, so you can do:

```ts
window.$crisp.push('safe', true);
```

---

I made a PR where I'm adding the method to handle it. [See here](https://github.com/crisp-im/crisp-sdk-web/pull/2)

**Comment by jashok2** [comment]
i got a mirror in vue3

index.ts:173 Refused to load the script 'https://client.crisp.chat/l.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

what should i do?

**Comment by baptistejamin** [comment]
@jashok2 Your issue is absolutely not related. You should just edit your CSP policy as stated in the error message. Please check https://docs.crisp.chat/guides/others/whitelisting-our-systems/crisp-domain-names/

**Comment by baptistejamin** [comment]
Safe mode is not available : https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/npm/#configuration
